name = "paper-feed-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "PAPERS_KV"
id = "YOUR_KV_NAMESPACE_ID_HERE"  # Replace with your actual KV namespace ID

# Cron Triggers (daily at 9 AM UTC)
[triggers]
crons = ["0 9 * * *"]

# Routes (replace with your worker subdomain)
# routes = [
#   { pattern = "paper-feed.your-subdomain.workers.dev/*", zone_name = "workers.dev" }
# ]
