name = "twitter-paper-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding (same as main worker)
[[kv_namespaces]]
binding = "PAPERS_KV"
id = "e471e03e4cfe4d3c9cd914856e133a2a"

# Cron trigger - runs weekly on Mondays at 9:30 AM UTC
# Limited to weekly to stay under Twitter API quota (1500 tweets/month)
[triggers]
crons = ["30 9 * * 1"]

# CORS headers for your website
[vars]
ALLOWED_ORIGIN = "https://rohanv.me"
