name = "twitter-paper-worker-2"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding (same as other workers)
[[kv_namespaces]]
binding = "PAPERS_KV"
id = "e471e03e4cfe4d3c9cd914856e133a2a"

# Cron trigger - runs weekly on Thursdays at 10:00 AM UTC
# Limited to weekly to stay under Twitter API quota (1500 tweets/month)
[triggers]
crons = ["0 10 * * 4"]

# CORS headers for your website
[vars]
ALLOWED_ORIGIN = "https://rohanv.me"
