name = "paper-discovery-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "PAPERS_KV"
id = "e471e03e4cfe4d3c9cd914856e133a2a"

# Cron trigger - runs daily at 9 AM UTC
[triggers]
crons = ["0 9 * * *"]

# CORS headers for your website
[vars]
ALLOWED_ORIGIN = "https://rohanvinaik.github.io"
